export const LOGIN = 'LOGIN';
export const LOGIN_DATA_LOADED = 'LOGIN_DATA_LOADED';
export const LOGIN_API_ERROR = 'LOGIN_API_ERROR';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESSFULLY = 'LOGOUT_SUCCESSFULLY';
export const LOGOUT_API_ERROR = 'LOGOUT_API_ERROR';